### PR TITLE
small bug fix on about page.

### LINKED ISSUE #67: Bug on about page where it keeps locked on loading.
With the way about page is implemented, if the user navigates to another application and comes back to fogos.pt the contributors list will reload, making a new call to the API, but wont leave the loading state.
the preferred way would be to reuse the already fetched data, cached on the store's appState, since the contributors almost do not change.

### PR DESCRIPTION
**Pull request by 0rp3u**
closes #67
Reuses previous contributors list, and fixes a loading bug.

### CODE REVIEW

File: lib/screens/about/about.dart [hunk 1]
```diff
@@ -14,7 +14,8 @@ class About extends StatelessWidget {
     return new StoreConnector<AppState, AppState>(
         converter: (Store<AppState> store) => store.state,
         onInit: (store) {
-          store.dispatch(LoadContributorsAction());
+          if(!store.state.hasContributors)
+            store.dispatch(LoadContributorsAction());
```
Comment (guivazcabral) [inline lib/screens/about/about.dart]: always wrap if statements in curly braces

File: lib/screens/about/about.dart [hunk 2]
```diff
@@ -14,7 +14,8 @@ class About extends StatelessWidget {
     return new StoreConnector<AppState, AppState>(
         converter: (Store<AppState> store) => store.state,
         onInit: (store) {
```
Comment (guivazcabral) [inline lib/screens/about/about.dart]: add the store type
